export const DEFAULT_BOARD_TEMPLATES = [
  {
    name: 'Album Release',
    description: 'Complete workflow for releasing a full album',
    category: 'music-release',
    icon: '🎵',
    isOfficial: true,
    isPublic: true,
    tags: ['music', 'release', 'album'],
    columns: [
      { id: 'planning', name: 'Planning', position: 0, color: '#3B82F6' },
      { id: 'production', name: 'Production', position: 1, color: '#8B5CF6' },
      { id: 'marketing', name: 'Marketing', position: 2, color: '#EC4899' },
      { id: 'distribution', name: 'Distribution', position: 3, color: '#10B981' },
      { id: 'completed', name: 'Completed', position: 4, color: '#22C55E' },
    ],
    tasks: [
      // Planning
      {
        title: 'Define album concept and theme',
        columnId: 'planning',
        priority: 'high',
        dueOffset: -120,
      },
      {
        title: 'Create tracklist and song order',
        columnId: 'planning',
        priority: 'high',
        dueOffset: -110,
      },
      {
        title: 'Set release date and timeline',
        columnId: 'planning',
        priority: 'urgent',
        dueOffset: -100,
      },
      {
        title: 'Budget planning and allocation',
        columnId: 'planning',
        priority: 'high',
        dueOffset: -100,
      },

      // Production
      {
        title: 'Record all tracks',
        columnId: 'production',
        priority: 'urgent',
        dueOffset: -90,
        labels: ['studio'],
      },
      {
        title: 'Mixing and mastering',
        columnId: 'production',
        priority: 'high',
        dueOffset: -60,
        labels: ['audio'],
      },
      {
        title: 'Album artwork and design',
        columnId: 'production',
        priority: 'high',
        dueOffset: -70,
        labels: ['design'],
      },
      {
        title: 'Photo shoot for promo materials',
        columnId: 'production',
        priority: 'medium',
        dueOffset: -65,
        labels: ['visual'],
      },
      {
        title: 'Music videos production',
        columnId: 'production',
        priority: 'medium',
        dueOffset: -50,
        labels: ['video'],
      },

      // Marketing
      {
        title: 'Create marketing strategy',
        columnId: 'marketing',
        priority: 'high',
        dueOffset: -80,
      },
      {
        title: 'Build pre-save campaign',
        columnId: 'marketing',
        priority: 'high',
        dueOffset: -45,
        labels: ['digital'],
      },
      {
        title: 'Press kit and EPK',
        columnId: 'marketing',
        priority: 'medium',
        dueOffset: -40,
        labels: ['press'],
      },
      {
        title: 'Social media content calendar',
        columnId: 'marketing',
        priority: 'medium',
        dueOffset: -35,
        labels: ['social'],
      },
      {
        title: 'Reach out to playlist curators',
        columnId: 'marketing',
        priority: 'high',
        dueOffset: -30,
        labels: ['promotion'],
      },
      {
        title: 'Radio promotion campaign',
        columnId: 'marketing',
        priority: 'medium',
        dueOffset: -25,
        labels: ['radio'],
      },
      {
        title: 'PR and media outreach',
        columnId: 'marketing',
        priority: 'high',
        dueOffset: -20,
        labels: ['press'],
      },

      // Distribution
      {
        title: 'Upload to distributors (DistroKid, TuneCore, etc.)',
        columnId: 'distribution',
        priority: 'urgent',
        dueOffset: -30,
      },
      {
        title: 'Submit to streaming platforms',
        columnId: 'distribution',
        priority: 'urgent',
        dueOffset: -28,
        labels: ['digital'],
      },
      {
        title: 'Physical manufacturing (CD/Vinyl)',
        columnId: 'distribution',
        priority: 'medium',
        dueOffset: -60,
        labels: ['physical'],
      },
      {
        title: 'Set up merch store',
        columnId: 'distribution',
        priority: 'low',
        dueOffset: -20,
        labels: ['merch'],
      },
    ],
  },

  {
    name: 'Single Release',
    description: 'Quick workflow for releasing a single track',
    category: 'music-release',
    icon: '🎤',
    isOfficial: true,
    isPublic: true,
    tags: ['music', 'release', 'single'],
    columns: [
      { id: 'todo', name: 'To Do', position: 0 },
      { id: 'in-progress', name: 'In Progress', position: 1 },
      { id: 'review', name: 'Review', position: 2 },
      { id: 'done', name: 'Done', position: 3 },
    ],
    tasks: [
      { title: 'Finalize track production', columnId: 'todo', priority: 'urgent', dueOffset: -21 },
      {
        title: 'Mixing and mastering',
        columnId: 'todo',
        priority: 'high',
        dueOffset: -18,
        labels: ['audio'],
      },
      {
        title: 'Create cover art',
        columnId: 'todo',
        priority: 'high',
        dueOffset: -15,
        labels: ['design'],
      },
      { title: 'Upload to distributor', columnId: 'todo', priority: 'urgent', dueOffset: -14 },
      {
        title: 'Set up pre-save campaign',
        columnId: 'todo',
        priority: 'high',
        dueOffset: -10,
        labels: ['marketing'],
      },
      {
        title: 'Submit to Spotify editorial',
        columnId: 'todo',
        priority: 'high',
        dueOffset: -7,
        labels: ['playlist'],
      },
      {
        title: 'Create social media teasers',
        columnId: 'todo',
        priority: 'medium',
        dueOffset: -7,
        labels: ['social'],
      },
      {
        title: 'Pitch to playlist curators',
        columnId: 'todo',
        priority: 'medium',
        dueOffset: -5,
        labels: ['promotion'],
      },
      {
        title: 'Release day social posts',
        columnId: 'todo',
        priority: 'high',
        dueOffset: 0,
        labels: ['social'],
      },
    ],
  },

  {
    name: 'Music Video Release',
    description: 'Production and release workflow for music videos',
    category: 'music-release',
    icon: '🎬',
    isOfficial: true,
    isPublic: true,
    tags: ['video', 'visual', 'release'],
    columns: [
      { id: 'pre-production', name: 'Pre-Production', position: 0 },
      { id: 'production', name: 'Production', position: 1 },
      { id: 'post-production', name: 'Post-Production', position: 2 },
      { id: 'promotion', name: 'Promotion', position: 3 },
      { id: 'complete', name: 'Complete', position: 4 },
    ],
    tasks: [
      {
        title: 'Concept development',
        columnId: 'pre-production',
        priority: 'high',
        dueOffset: -60,
      },
      { title: 'Storyboarding', columnId: 'pre-production', priority: 'high', dueOffset: -55 },
      {
        title: 'Location scouting',
        columnId: 'pre-production',
        priority: 'medium',
        dueOffset: -50,
      },
      {
        title: 'Casting and crew hiring',
        columnId: 'pre-production',
        priority: 'high',
        dueOffset: -45,
      },
      {
        title: 'Equipment and gear planning',
        columnId: 'pre-production',
        priority: 'medium',
        dueOffset: -40,
      },
      {
        title: 'Video shoot',
        columnId: 'production',
        priority: 'urgent',
        dueOffset: -30,
        labels: ['filming'],
      },
      { title: 'Video editing', columnId: 'post-production', priority: 'high', dueOffset: -20 },
      { title: 'Color grading', columnId: 'post-production', priority: 'medium', dueOffset: -15 },
      {
        title: 'VFX and graphics',
        columnId: 'post-production',
        priority: 'medium',
        dueOffset: -12,
      },
      {
        title: 'Final review and approval',
        columnId: 'post-production',
        priority: 'high',
        dueOffset: -7,
      },
      { title: 'Upload to YouTube', columnId: 'promotion', priority: 'urgent', dueOffset: -3 },
      {
        title: 'Create video teasers',
        columnId: 'promotion',
        priority: 'medium',
        dueOffset: -5,
        labels: ['social'],
      },
      {
        title: 'Submit to music video channels',
        columnId: 'promotion',
        priority: 'low',
        dueOffset: -2,
      },
      { title: 'Premiere event/watch party', columnId: 'promotion', priority: 'low', dueOffset: 0 },
    ],
  },

  {
    name: 'Paid Media Campaign',
    description: 'Manage paid advertising campaigns across platforms',
    category: 'marketing',
    icon: '📢',
    isOfficial: true,
    isPublic: true,
    tags: ['marketing', 'advertising', 'paid media'],
    columns: [
      { id: 'strategy', name: 'Strategy', position: 0 },
      { id: 'creative', name: 'Creative', position: 1 },
      { id: 'setup', name: 'Setup', position: 2 },
      { id: 'active', name: 'Active', position: 3 },
      { id: 'optimize', name: 'Optimize', position: 4 },
    ],
    tasks: [
      {
        title: 'Define campaign objectives',
        columnId: 'strategy',
        priority: 'urgent',
        dueOffset: -30,
      },
      { title: 'Set budget and timeline', columnId: 'strategy', priority: 'high', dueOffset: -28 },
      {
        title: 'Audience targeting research',
        columnId: 'strategy',
        priority: 'high',
        dueOffset: -25,
      },
      {
        title: 'Platform selection (Meta, TikTok, Google)',
        columnId: 'strategy',
        priority: 'medium',
        dueOffset: -22,
      },
      {
        title: 'Create ad creatives (images/videos)',
        columnId: 'creative',
        priority: 'high',
        dueOffset: -20,
        labels: ['design'],
      },
      {
        title: 'Write ad copy and CTAs',
        columnId: 'creative',
        priority: 'high',
        dueOffset: -18,
        labels: ['copywriting'],
      },
      {
        title: 'Set up tracking pixels',
        columnId: 'setup',
        priority: 'high',
        dueOffset: -15,
        labels: ['technical'],
      },
      { title: 'Create campaign structure', columnId: 'setup', priority: 'high', dueOffset: -12 },
      { title: 'Launch campaigns', columnId: 'active', priority: 'urgent', dueOffset: -7 },
      {
        title: 'Daily performance monitoring',
        columnId: 'active',
        priority: 'high',
        dueOffset: -5,
      },
      { title: 'A/B testing variations', columnId: 'optimize', priority: 'medium', dueOffset: -3 },
      { title: 'Budget optimization', columnId: 'optimize', priority: 'high', dueOffset: 0 },
    ],
  },

  {
    name: 'Catalog Marketing',
    description: 'Promote existing catalog and back catalog',
    category: 'marketing',
    icon: '📚',
    isOfficial: true,
    isPublic: true,
    tags: ['catalog', 'marketing', 'evergreen'],
    columns: [
      { id: 'audit', name: 'Audit', position: 0 },
      { id: 'planning', name: 'Planning', position: 1 },
      { id: 'execution', name: 'Execution', position: 2 },
      { id: 'monitoring', name: 'Monitoring', position: 3 },
    ],
    tasks: [
      {
        title: 'Catalog performance analysis',
        columnId: 'audit',
        priority: 'high',
        dueOffset: -20,
      },
      {
        title: 'Identify high-potential tracks',
        columnId: 'audit',
        priority: 'high',
        dueOffset: -18,
      },
      {
        title: 'Playlist research and curation',
        columnId: 'planning',
        priority: 'medium',
        dueOffset: -15,
      },
      {
        title: 'Content creation for social media',
        columnId: 'planning',
        priority: 'medium',
        dueOffset: -12,
        labels: ['content'],
      },
      {
        title: 'Pitch to playlist curators',
        columnId: 'execution',
        priority: 'high',
        dueOffset: -10,
      },
      {
        title: 'Launch social media campaigns',
        columnId: 'execution',
        priority: 'medium',
        dueOffset: -7,
        labels: ['social'],
      },
      { title: 'Influencer outreach', columnId: 'execution', priority: 'low', dueOffset: -5 },
      {
        title: 'Track performance metrics',
        columnId: 'monitoring',
        priority: 'high',
        dueOffset: 0,
      },
    ],
  },
];
